language: rust
cache: cargo

script:
  - cargo build --verbose
  - cargo build --verbose --features debug_utils
  - cargo build --verbose --release

rust:
  - stable
  - beta
  - nightly

os:
  - osx
  - windows
  - linux

matrix:
  allow_failures:
    - rust: nightly
